In [1]:
import pandas as pd

In [2]:
df4eda = pd.read_csv('df4eda.csv', index_col=0)
df4eda = df4eda.drop(['RunningMonths', 'Running Year', 'Running Months',
                     'Rolling Period', 'Rolling Period Sort'], axis = 1)
df4eda

/tmp/ipykernel_127/109050648.py:1: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df4eda = pd.read_csv('df4eda.csv', index_col=0)

,ProductID,Date,Zip,Units,Revenue_T,Manufacturer,Category,Segment,Product,isVanArsdel,...,Month,Quarter,Year,MonthIndex,City,State,Region,District,ManufacturerID_y,MfgisVanArsdel
0,981,2014-12-30,6111,12,31676.40,Natura,Urban,Convenience,Natura UC-44,No,...,Dec-14,Q4,2014,192,"Newington, CT",CT,East,District #02,8,No
1,1086,2014-12-30,92879,7,11020.59,Pirum,Rural,Productivity,Pirum RP-32,No,...,Dec-14,Q4,2014,192,"Corona, CA",CA,West,District #38,10,No
2,1085,2014-12-30,92879,7,11020.59,Pirum,Rural,Productivity,Pirum RP-31,No,...,Dec-14,Q4,2014,192,"Corona, CA",CA,West,District #38,10,No
3,489,2014-12-30,32901,3,35010.36,VanArsdel,Urban,Moderation,Maximus UM-94,Yes,...,Dec-14,Q4,2014,192,"Melbourne, FL",FL,East,District #10,7,Yes
4,1989,2014-12-30,84770,3,16441.11,Currus,Rural,Select,Currus RS-08,No,...,Dec-14,Q4,2014,192,"Saint George, UT",UT,West,District #38,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,990,2002-04-30,11752,1,5291.37,Natura,Urban,Convenience,Natura UC-53,No,...,Apr-02,Q2,2002,40,"Islip Terrace, NY",NY,East,District #03,8,No
1048571,990,2002-04-30,39367,1,5291.37,Natura,Urban,Convenience,Natura UC-53,No,...,Apr-02,Q2,2002,40,"Waynesboro, MS",MS,Central,District #24,8,No
1048572,2169,2002-04-30,98311,1,6614.37,Victoria,Urban,Extreme,Victoria UE-22,No,...,Apr-02,Q2,2002,40,"Bremerton, WA",WA,West,District #34,14,No
1048573,1144,2002-04-30,95018,1,4976.37,Pirum,Urban,Regular,Pirum UR-01,No,...,Apr-02,Q2,2002,40,"Felton, CA",CA,West,District #36,10,No
1048574,1144,2002-04-30,98682,1,4976.37,Pirum,Urban,Regular,Pirum UR-01,No,...,Apr-02,Q2,2002,40,"Vancouver, WA",WA,West,District #34,10,No

In [3]:
list_csv = ['df_abc_xyz_out__2014.csv', 'df_abc_xyz_out__2013.csv','df_abc_xyz_out__2012.csv',
           'df_abc_xyz_out__2011.csv', 'df_abc_xyz_out__2010.csv','df_abc_xyz_out__2009.csv',
           'df_abc_xyz_out__2008.csv', 'df_abc_xyz_out__2007.csv','df_abc_xyz_out__2006.csv',
           'df_abc_xyz_out__2005.csv', 'df_abc_xyz_out__2004.csv','df_abc_xyz_out__2003.csv']

list_year = [2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003]

In [4]:
df = pd.DataFrame()

In [5]:
for i in range(0, len(list_csv)):
    df_abcxyz = pd.read_csv(list_csv[i], index_col=0)
    #df_abcxyz
    
    # взять год склеить их по Product ID по году
    dfyear = df4eda[df4eda['Year']==list_year[i]].merge(df_abcxyz, how = 'left', left_on = 'ProductID', right_on = 'ProductID')
#    print(dfyear['Year'].unique)
#    df = pd.concat([df, dfyear], axis=1, ignore_index=True)
    df = pd.concat([df, dfyear], ignore_index=True)
#    print(df.info())

In [6]:
df

,ProductID,Date,Zip,Units,Revenue_T,Manufacturer,Category,Segment,Product,isVanArsdel,...,Year,MonthIndex,City,State,Region,District,ManufacturerID_y,MfgisVanArsdel,abc_class,xyz_class
0,981,2014-12-30,6111,12,31676.40,Natura,Urban,Convenience,Natura UC-44,No,...,2014,192,"Newington, CT",CT,East,District #02,8,No,B,Y
1,1086,2014-12-30,92879,7,11020.59,Pirum,Rural,Productivity,Pirum RP-32,No,...,2014,192,"Corona, CA",CA,West,District #38,10,No,B,Y
2,1085,2014-12-30,92879,7,11020.59,Pirum,Rural,Productivity,Pirum RP-31,No,...,2014,192,"Corona, CA",CA,West,District #38,10,No,B,Y
3,489,2014-12-30,32901,3,35010.36,VanArsdel,Urban,Moderation,Maximus UM-94,Yes,...,2014,192,"Melbourne, FL",FL,East,District #10,7,Yes,A,Y
4,1989,2014-12-30,84770,3,16441.11,Currus,Rural,Select,Currus RS-08,No,...,2014,192,"Saint George, UT",UT,West,District #38,4,No,A,Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976497,2388,2003-01-01,11776,1,3716.37,Aliqui,Urban,Convenience,Aliqui UC-36,No,...,2003,49,"Port Jefferson Station, NY",NY,East,District #03,2,No,A,Y
976498,2406,2003-01-01,34293,1,1070.37,Aliqui,Youth,Youth,Aliqui YY-15,No,...,2003,49,"Venice, FL",FL,East,District #10,2,No,C,Y
976499,1086,2003-01-01,84660,1,1070.37,Pirum,Rural,Productivity,Pirum RP-32,No,...,2003,49,"Spanish Fork, UT",UT,West,District #33,10,No,B,X
976500,2396,2003-01-01,16406,1,1070.37,Aliqui,Youth,Youth,Aliqui YY-05,No,...,2003,49,"Conneautville, PA",PA,East,District #13,2,No,A,X
976501,1085,2003-01-01,84660,1,1070.37,Pirum,Rural,Productivity,Pirum RP-31,No,...,2003,49,"Spanish Fork, UT",UT,West,District #33,10,No,B,X

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 976502 entries, 0 to 976501
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ProductID         976502 non-null  int64
 1   Date              976502 non-null  object
 2   Zip               976502 non-null  int64
 3   Units             976502 non-null  int64
 4   Revenue_T         976502 non-null  float64
 5   Manufacturer      976502 non-null  object
 6   Category          976502 non-null  object
 7   Segment           976502 non-null  object
 8   Product           976502 non-null  object
 9   isVanArsdel       976502 non-null  object
 10  IsCompeteHide     976502 non-null  object
 11  ManufacturerID_x  976502 non-null  int64
 12  IsCompete         976502 non-null  object
 13  MonthNo           976502 non-null  int64
 14  MonthName         976502 non-null  object
 15  MonthID           976502 non-null  int64
 16  Month             976502 non-null  object
 17  Quarter           976502 non-null  object
 18  Year              976502 non-null  int64
 19  MonthIndex        976502 non-null  int64
 20  City              976502 non-null  object
 21  State             976502 non-null  object
 22  Region            976502 non-null  object
 23  District          976502 non-null  object
 24  ManufacturerID_y  976502 non-null  int64
 25  MfgisVanArsdel    976502 non-null  object
 26  abc_class         976502 non-null  object
 27  xyz_class         976502 non-null  object
dtypes: float64(1), int64(9), object(18)
memory usage: 208.6+ MB

In [10]:
df['Year'].unique

<bound method Series.unique of 0         2014
1         2014
2         2014
3         2014
4         2014
          ...
976497    2003
976498    2003
976499    2003
976500    2003
976501    2003
Name: Year, Length: 976502, dtype: int64>

In [11]:
df.isnull().sum()

ProductID           0
Date                0
Zip                 0
Units               0
Revenue_T           0
Manufacturer        0
Category            0
Segment             0
Product             0
isVanArsdel         0
IsCompeteHide       0
ManufacturerID_x    0
IsCompete           0
MonthNo             0
MonthName           0
MonthID             0
Month               0
Quarter             0
Year                0
MonthIndex          0
City                0
State               0
Region              0
District            0
ManufacturerID_y    0
MfgisVanArsdel      0
abc_class           0
xyz_class           0
dtype: int64

In [12]:
df.to_csv('df_abc_xyz__2003_2014.csv')